spring:
  application:
    name: adminservice
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/seller_db
    username: postgres
    password: Kr12@984872
    pool:
      max-size: 20
      initial-size: 5
      validation-query: SELECT 1
    connection-factory:
      type: io.r2dbc.spi.ConnectionFactory

server:
  port: 8080

